# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ensm_cluster_mean <- function(Y_input, X_input, A_block_input, L, lambda_input = 1.0, eta_input = 1.0, sigma_py_input = 0.0, max_iter_input = 10L, a1_input = 0.01, a2_input = 10, b1_input = 0.001, b2_input = 1, alpha_sigma_input = 0.5, beta_sigma_input = 0.5, opt_method_input = 0L, opt_Y_input = 1L, priorA_input = 0L, priorB_input = 0L, Kmeans_initialize = FALSE, k_A = 0L, k_B = 0L, ks_A_ = NULL, ks_B_ = NULL, rho_input = 0.8, eps = 1e-3, split_frac_input = 0.1, A_or_B_first_input = 1.0, resampling_input = FALSE, gamma_init_A = NULL, gamma_init_B = NULL, w_init_ = NULL, sampleA_input = TRUE, sampleB_input = TRUE, last_islands = FALSE, verbose = TRUE) {
    .Call('_PARTOPT_ensm_cluster_mean', PACKAGE = 'PARTOPT', Y_input, X_input, A_block_input, L, lambda_input, eta_input, sigma_py_input, max_iter_input, a1_input, a2_input, b1_input, b2_input, alpha_sigma_input, beta_sigma_input, opt_method_input, opt_Y_input, priorA_input, priorB_input, Kmeans_initialize, k_A, k_B, ks_A_, ks_B_, rho_input, eps, split_frac_input, A_or_B_first_input, resampling_input, gamma_init_A, gamma_init_B, w_init_, sampleA_input, sampleB_input, last_islands, verbose)
}

